name: "Issue Retrieval"

on:
  issues:
    types: [opened]

jobs:
  trigger_workflow:
    uses: harkgill-amd/.github/.github/workflows/issue_labelling.yml@main
    with:
      issue_number: ${{ github.event.issue.number }}
      issue_title: ${{ github.event.issue.title }}
      issue_body: ${{ github.event.issue.body }}

